/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary2;


import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


/**
 *
 * @author admin
 */
public class MyFrame extends javax.swing.JFrame {
    
    //static Dictionary Dic = new Dictionary();
    static DictionaryManagement Dm = new DictionaryManagement();   
    static Frame f =new Frame(); 
    
    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputWord = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        outputWord = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDic = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary");
        setBackground(new java.awt.Color(255, 0, 0));

        inputWord.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputWordInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        inputWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputWordActionPerformed(evt);
            }
        });
        inputWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputWordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputWordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputWordKeyTyped(evt);
            }
        });

        searchButton.setText("Tìm từ cho bố");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add cmn từ");
        addButton.setToolTipText("Thêm từ vào từ điển");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Xóa cmn từ");
        deleteButton.setToolTipText("Xóa từ trong từ điển");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Bố mày thoát");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        outputWord.setBackground(new java.awt.Color(255, 255, 255));
        outputWord.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        outputWord.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        outputWord.setOpaque(true);
        outputWord.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        showDic.setModel(Dm.model);
        showDic.setToolTipText("");
        showDic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showDicMouseClicked(evt);
            }
        });
        showDic.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                showDicValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(showDic);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(inputWord))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputWord, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(exitButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchButton)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(inputWord, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(outputWord, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void inputWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputWordActionPerformed
        //nhập input tìm từ
        if(!inputWord.getText().equals("")){
            outputWord.setText("");
            String a = inputWord.getText();
            String b = (String)f.Dic.tm.get(a);
            if(b==null){
                b = "";
                JOptionPane.showMessageDialog(rootPane, "Từ chưa có trong từ điển");    
            }           
            outputWord.setText(b+"\n");
        }
        else JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập từ");
            
               
    }//GEN-LAST:event_inputWordActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        //
        if(!inputWord.getText().equals("")){
            outputWord.setText("");
            String a = inputWord.getText();
            String b = (String)f.Dic.tm.get(a);
            if(b==null){
                b = "";
                JOptionPane.showMessageDialog(rootPane, "Từ chưa có trong từ điển");
                  
            }              
            outputWord.setText(b+"\n");
            outputWord.setText(f.Dic.words[showDic.getSelectedIndex()].getWordExplain());
        }
        
            else JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập từ");
            
    }//GEN-LAST:event_searchButtonActionPerformed

    private void inputWordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputWordInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inputWordInputMethodTextChanged

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void showDicValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_showDicValueChanged
        //inputWord.setText(f.Dic.words[showDic.getSelectedIndex()].getWordTarget());
       //outputWord.setText(f.Dic.words[showDic.getSelectedIndex()].getWordExplain());
// TODO add your handling code here:
    }//GEN-LAST:event_showDicValueChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        f.setVisible(true);
        f.CreateAndShow();
        try {
            
            Dm.update(f.Dic);           
            showDic.setModel(Dm.model);
            showDic.show(true);
        } catch (IOException ex) {
            Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here
        //JOptionPane.showConfirmDialog(rootPane, "Bạn chắc muốn xóa từ này ?");
        //if(rootPane.equals("Yes")){
            String wordtarget = showDic.getSelectedValue();
            if(f.Dic.tm.containsKey(wordtarget)){
                f.Dic.tm.remove(wordtarget);
                try {
            
                    Dm.update(f.Dic);           
                    showDic.setModel(Dm.model);
                    
                } catch (IOException ex) {
                    Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
         
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void inputWordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputWordKeyTyped
       
    }//GEN-LAST:event_inputWordKeyTyped

    private void inputWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputWordKeyPressed
       
    }//GEN-LAST:event_inputWordKeyPressed

    private void inputWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputWordKeyReleased
        // TODO add your handling code here:
        if(!evt.equals(VK_ENTER)){
            String a = null;
        //outputWord.setText("");
        
            //outputWord.setText("");
            a = inputWord.getText();
            for(int i=0;i<f.Dic.getN();i++){
                String s = f.Dic.words[i].getWordTarget();
                
                if(s.startsWith(a)){   
                    showDic.setSelectedIndex(i);
                    break;                                    
                }
                
            }
            
        }
        
    }//GEN-LAST:event_inputWordKeyReleased

    private void showDicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showDicMouseClicked
        // TODO add your handling code here:
        
        inputWord.setText(f.Dic.words[showDic.getSelectedIndex()].getWordTarget());
        
    }//GEN-LAST:event_showDicMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dm.insertFromFile(f.Dic);
                new MyFrame().setVisible(true);
                
            }
        });
       
        		
	
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField inputWord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel outputWord;
    private javax.swing.JButton searchButton;
    private javax.swing.JList<String> showDic;
    // End of variables declaration//GEN-END:variables
}
